//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ability
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ability()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
        }
    
        public string Ability1 { get; set; }
        public Nullable<bool> Violent_Crime { get; set; }
        public Nullable<bool> Homicide { get; set; }
        public Nullable<bool> Robbery { get; set; }
        public Nullable<bool> Aggravated_Assault { get; set; }
        public Nullable<bool> Property_Crime { get; set; }
        public Nullable<bool> Burglary { get; set; }
        public Nullable<bool> Larceny { get; set; }
        public Nullable<bool> Motor_Vehicle_Theft { get; set; }
        public Nullable<bool> Arson { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
    }
}
