//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crime
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Crime()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
        }
    
        public string State { get; set; }
        public double Population { get; set; }
        public double Violent_Crime { get; set; }
        public double Homicide { get; set; }
        public double Rape_Revised { get; set; }
        public double Robbery { get; set; }
        public double Aggravated_Assault { get; set; }
        public double Property_Crime { get; set; }
        public double Burglary { get; set; }
        public double Larceny { get; set; }
        public double Motor_Vehicle_Theft { get; set; }
        public double Arson { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
    }
}
