//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserItem
    {
        public int UserItemId { get; set; }
        public string UserId { get; set; }
        public int ItemId { get; set; }
        public int Quantity { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
